server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://dbinstance.cwlk8zfdg6gh.us-east-2.rds.amazonaws.com:3306/departmentservice
    username: admin
    password: Password123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  application:
    name: DEPARTMENT-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost